version: '3.7'
services:
  ui:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: 
      context: .
    restart: always
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      - mongo
  ffmpeg:
    image: adilm7177/ffmpeg
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
    - ./data:/data/db
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data